### PR TITLE
Add shields

### PR DESCRIPTION
**Pull request by steven-joruk**
Procrastinating :smile:

### CODE REVIEW

**Review by dfrankland — APPROVED** [review]

**Comment by steven-joruk** [comment]
Mind if I rebase master to get rid of the merge commit?

**Comment by dfrankland** [comment]
Try out the rebase and merge option 😉 

Screen Shot 2020-04-04 at 1 01 27 PM

**Comment by steven-joruk** [comment]
I honestly didn't believe you 😆 , GitHub must be doing some magic to get rid of the merge commit. Thanks for the tip.

**Comment by dfrankland** [comment]
Not a problem! Also, I sent you an invite for managing these crates on crates.io. Feel free to accept and publish these changes whenever you'd like.

**Pull request merged**
