### PR TITLE
Split xpc-connection-sys into separate crate

### PR DESCRIPTION
**Pull request by archaelus**
Hi there, this PR splits the xpc-connection crate into two, a low level xpc-connection-sys crate with just the bindgen parts, and a the existing higher level xpc-connection crate. A cargo workspace has been created to hold both crates.

The bindgen recipe is updated to whitelist the types, variables, and functions that FFI is emitted for, which should cut compilation times a bit too.

Now:
* cargo test still works
* There is a -sys crate for other crates needing low level xpc framework access (I have one in the works for the VMNet framework)
* Versions numbers for crates.io still need updating.

Is there anything I can help with to get this landed? Thanks for your crate!

### CODE REVIEW

**Review by dfrankland — APPROVED** [review]
Looks great!

**Comment by dfrankland** [comment]
Both packages are now published:
https://crates.io/crates/xpc-connection
https://crates.io/crates/xpc-connection-sys

Thanks again!

**Comment by archaelus** [comment]
Whoops - I forgot to set the -sys crate version to 0.2.2 - it's at 0.1 now.

**Comment by dfrankland** [comment]
Er, I did that actually. I was under the impression they'd be versioned separately so I just reset the clock on the -sys crate. Does that cause any problems? I might be missing something 🤔

**Pull request merged**
