### PR TITLE
Don't use Vec::from_raw_parts

### PR DESCRIPTION
**Pull request by steven-joruk**
It has extremely strict restrictions that we can't fullfil.

More importantly, we don't own the data given to us, so once we take the value and drop it, it causes a crash when libdispatch attempts to free a NULL pointer. I'm on macOS 10.15.3 in case you're unable to reproduce it.

Most of the time it fails like this:
```
running 1 test
Got data! Ok(Dictionary({"kCBMsgArgs": Dictionary({"kCBAdvDataDeviceAddress": Data([255, 255, 255, 255, 255, 255])}), "kCBMsgId": Int64(42)}))
integration_test-e211cc896451940c(79566,0x700003cfa000) malloc: *** error for object 0x7ff864c04d90: pointer being freed was not allocated
integration_test-e211cc896451940c(79566,0x700003cfa000) malloc: *** set a breakpoint in malloc_error_break to debug
```
But other times I have seen it segfault.

After fixing this, I now see the second assertion fail:
```
    // Can't get data when the channel is closed by dropping `xpc_connection`
    xpc_connection.send_message(message);
    drop(xpc_connection);
    assert!(blocking_stream.next().is_none());
```

Is this test valid? `XpcConnection::connect` returns a clone of the UnboundReceiver, so I'm not sure that the connection being dropped should cause the clone to be unusable.

### CODE REVIEW

**Comment by dfrankland** [comment]
Dope! Thank you for this

**Comment by dfrankland** [comment]
I've just published this under 0.2.3 👍

**Comment by steven-joruk** [comment]
That was quick, thanks :). I'm not sure if you saw the question at the end though, about the last assert?

**Comment by dfrankland** [comment]
Sorry about that! I did totally miss that.

`block_on_stream` should block until a value is returned from the `UnboundedReceiver`, unless the `UnboundedReceiver` is closed. Dropping the `UnboundedReceiver` should close it, which in turn makes the `blocking_stream` return `None`.

All the tests pass as of right now on `master`. I double checked the negative test case and commented out the `drop` and then the test fails.

**Pull request merged**
